# Generated by Django 5.0.1 on 2026-01-17 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jingleschedule",
            name="venue_name",
            field=models.CharField(
                blank=True,
                help_text="Optional: Venue name to filter schedules (e.g., 'Admiral Rodney'). Leave empty for all venues.",
                max_length=200,
                null=True,
            ),
        ),
    ]
