# Generated by Django 5.0.1 on 2026-01-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_multiple_choice_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="pubquizsession",
            name="session_code",
            field=models.CharField(
                default="TEMP0000",
                editable=False,
                help_text="Random 8-character code for URL access",
                max_length=8,
                unique=True,
            ),
        ),
    ]
