# Generated by Django 5.0.1 on 2026-01-23 05:23

from django.db import migrations, models
import secrets
import string


def generate_unique_codes(apps, schema_editor):
    """Generate unique session codes for existing sessions"""
    PubQuizSession = apps.get_model('api', 'PubQuizSession')
    
    def generate_code():
        """Generate a random 8-character alphanumeric code"""
        chars = string.ascii_uppercase + string.digits
        # Remove confusing characters
        chars = chars.replace('O', '').replace('0', '').replace('I', '').replace('1', '')
        return ''.join(secrets.choice(chars) for _ in range(8))
    
    existing_codes = set()
    for session in PubQuizSession.objects.all():
        # Generate unique code
        while True:
            code = generate_code()
            if code not in existing_codes:
                existing_codes.add(code)
                session.session_code = code
                session.save(update_fields=['session_code'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_add_multiple_choice_questions"),
    ]

    operations = [
        # Step 1: Add field without unique constraint
        migrations.AddField(
            model_name="pubquizsession",
            name="session_code",
            field=models.CharField(
                default="TEMP0000",
                editable=False,
                help_text="Random 8-character code for URL access",
                max_length=8,
                unique=False,  # Not unique yet
            ),
        ),
        # Step 2: Generate unique codes for existing sessions
        migrations.RunPython(generate_unique_codes, reverse_code=migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name="pubquizsession",
            name="session_code",
            field=models.CharField(
                default="TEMP0000",
                editable=False,
                help_text="Random 8-character code for URL access",
                max_length=8,
                unique=True,
            ),
        ),
    ]
