# Generated by Django 5.0.1 on 2026-01-27 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_auto_advance_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pubquizsession",
            name="auto_advance_enabled",
            field=models.BooleanField(
                default=True, help_text="Auto-advance to next question"
            ),
        ),
        migrations.CreateModel(
            name="BingoSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        help_text="Unique session identifier (UUID)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "venue_name",
                    models.CharField(help_text="Pub or venue name", max_length=200),
                ),
                (
                    "host_name",
                    models.CharField(
                        blank=True,
                        help_text="Optional host/DJ name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "num_players",
                    models.IntegerField(
                        default=25,
                        help_text="Number of players (affects song selection)",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "voice_id",
                    models.CharField(
                        default="JBFqnCBsd6RMkjVDRZzb",
                        help_text="ElevenLabs voice ID for announcements",
                        max_length=100,
                    ),
                ),
                (
                    "decades",
                    models.JSONField(
                        default=list,
                        help_text="Selected decades (e.g., ['1960s', '1970s', '1980s'])",
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(blank=True, help_text="URL to pub logo", null=True),
                ),
                (
                    "social_media",
                    models.CharField(
                        blank=True,
                        help_text="Social media URL for QR code",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "include_qr",
                    models.BooleanField(
                        default=False, help_text="Include QR code on cards"
                    ),
                ),
                (
                    "prizes",
                    models.JSONField(
                        default=dict,
                        help_text="Prize information (4corners, first_line, full_house)",
                    ),
                ),
                (
                    "songs_played",
                    models.JSONField(
                        default=list,
                        help_text="Array of song IDs that have been played",
                    ),
                ),
                (
                    "current_song_index",
                    models.IntegerField(
                        default=0, help_text="Current position in song pool"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        help_text="Current session status",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["venue_name", "-created_at"],
                        name="api_bingose_venue_n_79397e_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="api_bingose_status_a911a5_idx",
                    ),
                ],
            },
        ),
    ]
