# Generated by Django 5.0.1 on 2026-01-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_pubquizsession_auto_advance_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bingosession",
            name="logo_url",
            field=models.URLField(
                blank=True, help_text="URL to pub logo", max_length=1000, null=True
            ),
        ),
    ]
