# Generated by Django 5.0.1 on 2026-01-28 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_taskstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="jingleschedule",
            name="session",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: Specific bingo session. If set, this schedule applies only to this session. If null, uses venue_name filtering.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jingle_schedules",
                to="api.bingosession",
            ),
        ),
    ]
